pipeline {
    agentany
    tools {
        maven 'MAVEN'
    }
    stages {
        stage("build jar") {
            steps {
                script {
                    echo "building the application..."
                    sh "mvn package"
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "building the docker image..."
                    withCredentials ([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')])
                        sh 'docker build -t Rakhi2421/demo-app:jma-1.0 .'
                        sh "echo ${PASS} | docker login -u ${USER} --password-stdin  "
                        sh 'docker push Rakhi2421/demo-app:jma-1.0 '
                }
            }
        }
    }

}


// Full Pipeline using Groovy Script
def gv

pipeline {
    agentany
    tools {
        maven 'MAVEN'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy" 
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    gv.buildAPP
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    gv.buildImage
                }
            }
        }
    }

}