def gv

pipeline {
    agentany
    parameters{
        choice (name: 'VERSION',choices: ['1.1.0', '1.2.0', '1.3.0'],description: '')
        booleanParam (name: 'executeTests', defaultValue: true, description: '')
    }

    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy"             
                }
            }
        }
        stage("build") {
            steps {
                script {
                    gv.buildAPP()
                }
            }
        }
        stage("test") {
            //we can define conditionals for each stage
            when {
                expression {
                    BRANCH_NAME == 'dev' || BRANCH_NAME == 'test'  
                     // this means this test executes when branch is either test or dev, unless it will skipped.
                }
            }
            steps {
                script {
                    gv.testApp()
                }
            }
        }
        stage("deploy") {
            when {
                expression {
                    params.executeTests
               }
            }
            input {
              message "Select environment to deploy to"
              ok "Done"
              parameters {
                  choice (name: 'ENV-1',choices: ['dev', 'staging', 'prod'],description: '')
                  // deploy at a time on 2 environments
                  choice (name: 'ENV-2',choices: ['dev', 'staging', 'prod'],description: '')
              }
            }
            steps {
                script {
                    // using input parameter for user directly in script
                    env.ENV = input message: "Select environment to deploy to", ok: "Done", parameters: [choice (name: 'ENV',choices: ['dev', 'staging', 'prod'],description: '')]
                    gv.deployApp ()
                    echo "deploying to ${ENV}"
                    echo "deploying to ${ENV-1}"
                    echo "deploying to ${ENV-2}"
                }
                withCredentials([
                    usernamePassword(credentials: 'server-credentials', usernameVariable: USER, passwordVariable: PWD)
                ]) {
                    sh "some script ${USER} ${PWD}"
                }
            }
        }
    }
    // Post is used to Executes some logic after all stages executed.
    // In Post we have to use some conditions like always, success, failure,....
    // It is mostly used to notify us when a build is succeeded or failed
    post {                    
        always {
            //
        }
        success {

        }
    }
}